# Spring properties
spring:
  application:
     name: second-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5 

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port
